[package]
name = "chessehc_server"
version = "0.1.7"
authors = ["Tom Boddaert (tomBoddaert) <chessehc@tomboddaert.com>", "BigPharmaceutical"]
edition = "2021"
description = "A variation of Chess on the surface of a tube; server and library"
readme = "../README.md"
homepage = "https://github.com/BigPharmaceutical/chessehc/"
repository = "https://github.com/BigPharmaceutical/chessehc/"
license = "MIT OR Apache-2.0"

[dependencies]

[lib]
name = "chessehc"
path = "lib/lib.rs"
doc = true
edition = "2021"
crate-type = [ "lib" ]

[features]
standard_pieces = []
server = []
default = [ "standard_pieces" ]

[[bin]]
name = "chessehc_server"
path = "src/main.rs"
# required-features = [ "server" ]
