name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy --verbose --features server
    - name: Build
      run: cargo build --verbose --features server
    - name: Run tests
      run: cargo test --verbose --features server
